// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbomjxtuhjmutrqjjlhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRib21qeHR1aGptdXRycWpqbGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzAyODMsImV4cCI6MjA2MjM0NjI4M30.48dBm0LUBWxXyhcR9F8pBLPnVpaydYCcsR3QLOsXbiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);